# Generated by Django 4.2.5 on 2024-05-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alert_overallalert_customuser_joined_referral_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='OverallAlert',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='joined_referral_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_referral_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_id',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
