# Generated by Django 4.2.5 on 2024-05-19 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alert_overallalert_customuser_joined_referral_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_referrals', models.PositiveIntegerField(default=0)),
                ('plan', models.IntegerField(blank=True, choices=[(10, '$10'), (100, '$100'), (200, '$200'), (500, '$500'), (800, '$800'), (1000, '$1000')], null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('parent_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_referrals', to=settings.AUTH_USER_MODEL)),
                ('user_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
