# Generated by Django 4.2.5 on 2024-05-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='joined_referrals',
        ),
    ]
