# Generated by Django 4.2.5 on 2024-05-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
