# Generated by Django 5.0.6 on 2024-06-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_wallet_w_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='w_id',
            new_name='walletId',
        ),
    ]
