# Generated by Django 5.0.6 on 2024-06-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_w_id_wallet_walletid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='walletId',
            new_name='w_id',
        ),
    ]
