# Generated by Django 5.0.6 on 2024-06-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_walletid_wallet_w_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='w_id',
        ),
    ]
