# Generated by Django 5.0.6 on 2024-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_wallet_w_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
